// <auto-generated />
namespace Kidzmile.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialDatabaseMigrationaddingfnamelnamecreatedtsupdatedtscolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialDatabaseMigrationaddingfnamelnamecreatedtsupdatedtscolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201810141129056_Initial Database Migration ,adding fname,lname,createdts,updatedts columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
